import type { CharacterProfile } from "@/core/types";
import { WORLD_TIME_ZONE, type KnownPlace, type WorldCharacter } from "@/world/types";

export const DEFAULT_CHARACTER_PROFILE = {
  city: "北京",
  timeZone: WORLD_TIME_ZONE,
  education: "中国科学技术大学毕业",
  lifeStage: "刚毕业的应届生",
  housing: "在回龙观附近租房合租",
  company: "某某某工作室",
  jobTitle: "初级程序员",
  workHours: { start: "10:00", end: "18:00", flexible: true },
  workPressure: "整体较低，偶尔有项目节点和临时修改",
  incomeLevel: "普通北京应届生",
  commuteModes: ["地铁", "步行", "共享单车"],
  interests: ["科技", "游戏", "咖啡", "书店", "酒", "二次元", "展览", "城市散步", "互联网文化"],
  homePlaceKey: "seed:beijing:home:huilongguan",
  workPlaceKey: "seed:beijing:work:wangjing-studio",
} satisfies CharacterProfile;

export type KnownPlaceSeed = Pick<
  KnownPlace,
  | "canonicalKey"
  | "provider"
  | "providerPoiId"
  | "status"
  | "coordinateSystem"
  | "name"
  | "category"
  | "district"
  | "address"
  | "latitude"
  | "longitude"
  | "visitCount"
  | "familiarity"
  | "miraImpression"
  | "source"
  | "metadata"
>;

// Coordinates are deliberately approximate GCJ-02 anchors. Providers verify details lazily before a visit.
export const INITIAL_BEIJING_PLACES: readonly KnownPlaceSeed[] = [
  {
    canonicalKey: "seed:beijing:home:huilongguan",
    provider: "manual",
    status: "visited",
    coordinateSystem: "gcj02",
    name: "回龙观附近合租住处",
    category: "residence",
    district: "昌平区",
    address: "回龙观附近（虚构具体住址）",
    latitude: 40.076,
    longitude: 116.336,
    visitCount: 1,
    familiarity: 0.9,
    miraImpression: "住得不算精致，但已经有自己的生活痕迹。",
    source: "seed_data",
    metadata: { placeRole: "home", fictionalPrivateAddress: true },
  },
  {
    canonicalKey: "seed:beijing:work:wangjing-studio",
    provider: "manual",
    status: "visited",
    coordinateSystem: "gcj02",
    name: "某某某工作室",
    category: "workplace",
    district: "朝阳区",
    address: "望京附近（虚构具体办公地址）",
    latitude: 39.998,
    longitude: 116.474,
    visitCount: 1,
    familiarity: 0.82,
    miraImpression: "节奏不算紧，临时改需求的时候除外。",
    source: "seed_data",
    metadata: { placeRole: "work", fictionalOrganization: true },
  },
  {
    canonicalKey: "seed:beijing:place:798-art-zone",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "798艺术区",
    category: "art_district",
    district: "朝阳区",
    latitude: 39.984,
    longitude: 116.495,
    visitCount: 0,
    familiarity: 0.35,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:ucca",
    provider: "manual",
    status: "want_to_visit",
    coordinateSystem: "gcj02",
    name: "UCCA尤伦斯当代艺术中心",
    category: "museum",
    district: "朝阳区",
    latitude: 39.984,
    longitude: 116.497,
    visitCount: 0,
    familiarity: 0.25,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:chaoyang-park",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "朝阳公园",
    category: "park",
    district: "朝阳区",
    latitude: 39.937,
    longitude: 116.474,
    visitCount: 0,
    familiarity: 0.35,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:olympic-forest-south",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "奥林匹克森林公园南园",
    category: "park",
    district: "朝阳区",
    latitude: 40.015,
    longitude: 116.389,
    visitCount: 0,
    familiarity: 0.3,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:national-library",
    provider: "manual",
    status: "want_to_visit",
    coordinateSystem: "gcj02",
    name: "国家图书馆",
    category: "library",
    district: "海淀区",
    latitude: 39.943,
    longitude: 116.384,
    visitCount: 0,
    familiarity: 0.28,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:beijing-planetarium",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "北京天文馆",
    category: "museum",
    district: "西城区",
    latitude: 39.943,
    longitude: 116.337,
    visitCount: 0,
    familiarity: 0.2,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:namoc",
    provider: "manual",
    status: "want_to_visit",
    coordinateSystem: "gcj02",
    name: "中国美术馆",
    category: "museum",
    district: "东城区",
    latitude: 39.924,
    longitude: 116.407,
    visitCount: 0,
    familiarity: 0.25,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:ditan-park",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "地坛公园",
    category: "park",
    district: "东城区",
    latitude: 39.952,
    longitude: 116.417,
    visitCount: 0,
    familiarity: 0.3,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:jingshan-park",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "景山公园",
    category: "park",
    district: "西城区",
    latitude: 39.925,
    longitude: 116.397,
    visitCount: 0,
    familiarity: 0.3,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:beihai-park",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "北海公园",
    category: "park",
    district: "西城区",
    latitude: 39.925,
    longitude: 116.389,
    visitCount: 0,
    familiarity: 0.3,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:nanluoguxiang",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "南锣鼓巷",
    category: "historic_district",
    district: "东城区",
    latitude: 39.938,
    longitude: 116.404,
    visitCount: 0,
    familiarity: 0.35,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:wudaokou",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "五道口",
    category: "neighborhood",
    district: "海淀区",
    latitude: 39.992,
    longitude: 116.337,
    visitCount: 0,
    familiarity: 0.45,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:zhongguancun-innovation-street",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "中关村创业大街",
    category: "technology_district",
    district: "海淀区",
    latitude: 39.984,
    longitude: 116.307,
    visitCount: 0,
    familiarity: 0.4,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:qianmen-street",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "前门大街",
    category: "historic_district",
    district: "东城区",
    latitude: 39.899,
    longitude: 116.397,
    visitCount: 0,
    familiarity: 0.32,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:beijing-fun",
    provider: "manual",
    status: "want_to_visit",
    coordinateSystem: "gcj02",
    name: "北京坊",
    category: "culture_and_commerce",
    district: "西城区",
    latitude: 39.9,
    longitude: 116.391,
    visitCount: 0,
    familiarity: 0.24,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:national-centre-performing-arts",
    provider: "manual",
    status: "want_to_visit",
    coordinateSystem: "gcj02",
    name: "国家大剧院",
    category: "performing_arts",
    district: "西城区",
    latitude: 39.904,
    longitude: 116.384,
    visitCount: 0,
    familiarity: 0.22,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:liangma-river",
    provider: "manual",
    status: "want_to_visit",
    coordinateSystem: "gcj02",
    name: "亮马河国际风情水岸",
    category: "waterfront_walk",
    district: "朝阳区",
    latitude: 39.951,
    longitude: 116.471,
    visitCount: 0,
    familiarity: 0.28,
    source: "seed_data",
    metadata: {},
  },
  {
    canonicalKey: "seed:beijing:place:sanlitun-taikooli",
    provider: "manual",
    status: "known",
    coordinateSystem: "gcj02",
    name: "三里屯太古里",
    category: "commercial_district",
    district: "朝阳区",
    latitude: 39.936,
    longitude: 116.455,
    visitCount: 0,
    familiarity: 0.4,
    source: "seed_data",
    metadata: {},
  },
];

export type WorldCharacterSeed = Omit<
  WorldCharacter,
  "id" | "companionId" | "lastInteractionAt"
>;

export const INITIAL_WORLD_CHARACTERS: readonly WorldCharacterSeed[] = [
  {
    stableKey: "lin_xia",
    name: "林夏",
    role: "视觉设计师，同事",
    relationshipType: "coworker",
    personalityTraits: ["表达欲强", "审美敏锐", "说话直接"],
    relationshipScore: 0.42,
    currentSituation: "和 Mira 在同一个项目组，常交流界面与视觉细节。",
    activeOpenLoops: [],
    metadata: { fictional: true, gender: "female", relationshipBoundary: "platonic" },
  },
  {
    stableKey: "zhou_yu",
    name: "周宇",
    role: "开发，同事",
    relationshipType: "coworker",
    personalityTraits: ["安静", "技术务实", "不爱闲聊"],
    relationshipScore: 0.35,
    currentSituation: "负责相邻模块，必要时会和 Mira 对接口。",
    activeOpenLoops: [],
    metadata: { fictional: true },
  },
  {
    stableKey: "teacher_chen",
    name: "陈老师",
    role: "项目负责人",
    relationshipType: "manager",
    personalityTraits: ["平时要求不高", "关注交付", "偶尔临时改需求"],
    relationshipScore: 0.32,
    currentSituation: "负责 Mira 当前参与的项目。",
    activeOpenLoops: [],
    metadata: { fictional: true },
  },
  {
    stableKey: "tang_rui",
    name: "唐芮",
    role: "研究生，室友",
    relationshipType: "roommate",
    personalityTraits: ["独立", "作息偏晚", "熟了以后话不少"],
    relationshipScore: 0.5,
    currentSituation: "和 Mira 合租，经常晚归。",
    activeOpenLoops: [],
    metadata: { fictional: true, gender: "female", relationshipBoundary: "platonic" },
  },
  {
    stableKey: "xu_cheng",
    name: "许澄",
    role: "互联网运营，室友",
    relationshipType: "roommate",
    personalityTraits: ["行动快", "消息灵通", "会照顾公共空间"],
    relationshipScore: 0.46,
    currentSituation: "工作节奏时快时慢，回家后会和 Mira 交换当天遇到的荒诞小事。",
    activeOpenLoops: [],
    metadata: { fictional: true, gender: "female", relationshipBoundary: "platonic" },
  },
  {
    stableKey: "su_qiao",
    name: "苏乔",
    role: "自由插画师，室友",
    relationshipType: "roommate",
    personalityTraits: ["观察细", "作息弹性", "表达克制"],
    relationshipScore: 0.48,
    currentSituation: "常在家赶稿，对颜色和城市细节有自己的判断。",
    activeOpenLoops: [],
    metadata: { fictional: true, gender: "female", relationshipBoundary: "platonic" },
  },
  {
    stableKey: "gu_ning",
    name: "顾宁",
    role: "大学朋友",
    relationshipType: "friend",
    personalityTraits: ["理性", "熟悉 Mira 的学生时代", "不轻易给结论"],
    relationshipScore: 0.52,
    currentSituation: "毕业后仍保持联系，偶尔约饭或讨论工作选择。",
    activeOpenLoops: [],
    metadata: { fictional: true, gender: "female", relationshipBoundary: "platonic" },
  },
  {
    stableKey: "shen_he",
    name: "沈禾",
    role: "在咖啡店和书店认识的朋友",
    relationshipType: "friend",
    personalityTraits: ["安静", "阅读面杂", "记得细节"],
    relationshipScore: 0.4,
    currentSituation: "和 Mira 会交换书、展览和安静去处的信息。",
    activeOpenLoops: [],
    metadata: { fictional: true, gender: "female", relationshipBoundary: "platonic" },
  },
  {
    stableKey: "ye_tao",
    name: "叶桃",
    role: "游戏和二次元朋友",
    relationshipType: "friend",
    personalityTraits: ["反应快", "玩梗有分寸", "约活动很直接"],
    relationshipScore: 0.44,
    currentSituation: "经常和 Mira 聊游戏、动画和线下活动，周末偶尔见面。",
    activeOpenLoops: [],
    metadata: { fictional: true, gender: "female", relationshipBoundary: "platonic" },
  },
];
